command:
  - "gunicorn"
  - "app:server"
  - "-w"
  - "4"
  - "-b"
  - "0.0.0.0:8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: GRAPHRAG_ENDPOINT_NAME
    valueFrom: serving-endpoint
  - name: DATABRICKS_CATALOG
    value: "serverless_8e8gyh_catalog"
  - name: DATABRICKS_SCHEMA
    value: "graphrag_bible"
  - name: USE_MOCK_BACKEND
    value: "false"
