"""Single source of truth for the complete Bible book registry (66 books).

Used by:
- src/config.py (Databricks notebook, via %run)
- src/app/pages/manage_corpus.py (Dash app)
"""

BIBLE_BOOKS_ALL: dict[str, dict] = {
    # --- Old Testament (39 books) ---
    "Genesis":        {"chapters": 50, "testament": "OT"},
    "Exodus":         {"chapters": 40, "testament": "OT"},
    "Leviticus":      {"chapters": 27, "testament": "OT"},
    "Numbers":        {"chapters": 36, "testament": "OT"},
    "Deuteronomy":    {"chapters": 34, "testament": "OT"},
    "Joshua":         {"chapters": 24, "testament": "OT"},
    "Judges":         {"chapters": 21, "testament": "OT"},
    "Ruth":           {"chapters": 4,  "testament": "OT"},
    "1Samuel":        {"chapters": 31, "testament": "OT"},
    "2Samuel":        {"chapters": 24, "testament": "OT"},
    "1Kings":         {"chapters": 22, "testament": "OT"},
    "2Kings":         {"chapters": 25, "testament": "OT"},
    "1Chronicles":    {"chapters": 29, "testament": "OT"},
    "2Chronicles":    {"chapters": 36, "testament": "OT"},
    "Ezra":           {"chapters": 10, "testament": "OT"},
    "Nehemiah":       {"chapters": 13, "testament": "OT"},
    "Esther":         {"chapters": 10, "testament": "OT"},
    "Job":            {"chapters": 42, "testament": "OT"},
    "Psalms":         {"chapters": 150, "testament": "OT"},
    "Proverbs":       {"chapters": 31, "testament": "OT"},
    "Ecclesiastes":   {"chapters": 12, "testament": "OT"},
    "SongofSolomon":  {"chapters": 8,  "testament": "OT"},
    "Isaiah":         {"chapters": 66, "testament": "OT"},
    "Jeremiah":       {"chapters": 52, "testament": "OT"},
    "Lamentations":   {"chapters": 5,  "testament": "OT"},
    "Ezekiel":        {"chapters": 48, "testament": "OT"},
    "Daniel":         {"chapters": 12, "testament": "OT"},
    "Hosea":          {"chapters": 14, "testament": "OT"},
    "Joel":           {"chapters": 3,  "testament": "OT"},
    "Amos":           {"chapters": 9,  "testament": "OT"},
    "Obadiah":        {"chapters": 1,  "testament": "OT"},
    "Jonah":          {"chapters": 4,  "testament": "OT"},
    "Micah":          {"chapters": 7,  "testament": "OT"},
    "Nahum":          {"chapters": 3,  "testament": "OT"},
    "Habakkuk":       {"chapters": 3,  "testament": "OT"},
    "Zephaniah":      {"chapters": 3,  "testament": "OT"},
    "Haggai":         {"chapters": 2,  "testament": "OT"},
    "Zechariah":      {"chapters": 14, "testament": "OT"},
    "Malachi":        {"chapters": 4,  "testament": "OT"},
    # --- New Testament (27 books) ---
    "Matthew":        {"chapters": 28, "testament": "NT"},
    "Mark":           {"chapters": 16, "testament": "NT"},
    "Luke":           {"chapters": 24, "testament": "NT"},
    "John":           {"chapters": 21, "testament": "NT"},
    "Acts":           {"chapters": 28, "testament": "NT"},
    "Romans":         {"chapters": 16, "testament": "NT"},
    "1Corinthians":   {"chapters": 16, "testament": "NT"},
    "2Corinthians":   {"chapters": 13, "testament": "NT"},
    "Galatians":      {"chapters": 6,  "testament": "NT"},
    "Ephesians":      {"chapters": 6,  "testament": "NT"},
    "Philippians":    {"chapters": 4,  "testament": "NT"},
    "Colossians":     {"chapters": 4,  "testament": "NT"},
    "1Thessalonians": {"chapters": 5,  "testament": "NT"},
    "2Thessalonians": {"chapters": 3,  "testament": "NT"},
    "1Timothy":       {"chapters": 6,  "testament": "NT"},
    "2Timothy":       {"chapters": 4,  "testament": "NT"},
    "Titus":          {"chapters": 3,  "testament": "NT"},
    "Philemon":       {"chapters": 1,  "testament": "NT"},
    "Hebrews":        {"chapters": 13, "testament": "NT"},
    "James":          {"chapters": 5,  "testament": "NT"},
    "1Peter":         {"chapters": 5,  "testament": "NT"},
    "2Peter":         {"chapters": 3,  "testament": "NT"},
    "1John":          {"chapters": 5,  "testament": "NT"},
    "2John":          {"chapters": 1,  "testament": "NT"},
    "3John":          {"chapters": 1,  "testament": "NT"},
    "Jude":           {"chapters": 1,  "testament": "NT"},
    "Revelation":     {"chapters": 22, "testament": "NT"},
}
